### ISSUE TITLE
Doesn't handle git dependencies very well

### ISSUE THREAD

**Issue by fivetanley** [ember-cli/ember-cli-version-checker#13]
In npm itself, a git specified version can satisfy a dependency if the checked out repository has a `package.json` with a `version` that matches the dependency's version.

For example, I would expect the following to work:

``` javascript
// app's package.json
{
  "name": "myapp",
  "dependencies": {
    "ember-pouch": "^1.x",
    "ember-data": "git+https://github.com/emberjs/ember-data#release/2.4.0"
  }
}
```

``` javascript
// ember-pouch's version checking code
var VersionChecker = require('ember-cli-version-checker');
var checker = new VersionChecker(this)
checker.for('ember-data', 'npm').assertAbove('2.4.0'); // should not throw exception
```

``` javascript
// ember-data's package.json from https://github.com/emberjs/ember-data#release/2.4.0
{
  "name": "ember-data",
  "version": "2.4.0"
}
```

I'm happy to implement a pull request for this feature if you agree this feature should be supported.

**Comment by rwjblue** [comment]
@fivetanley - Ya, I'm happy to follow NPM's lead here.  If a dep is specified with a non-semver range (like `git+https` in the example) then checking the `node_modules/<package-name>/package.json`'s `version` value seems like the right choice.

**Comment by rwjblue** [comment]
Would love a PR if you have time, I'm unsure if/when I'll have time to tackle myself.

**Comment by jamesarosen** [comment]
Similarly, there's no way to know what version of ember `beta` or `release` or `canary` is.

**Comment by Turbo87** [comment]
@rwjblue aren't we doing this already? is this issue obsolete?

**Comment by rwjblue** [comment]
I haven't been able to identify exactly what is the issue here, I _believe_ that in general we do the right thing?

**Comment by Turbo87** [comment]
well looking at https://github.com/ember-cli/ember-cli-version-checker/blob/master/index.js#L63-L74 we seem to already read the version from the `package.json` file inside the dependency, so I'm not sure if this issue is still relevant.

**Comment by gokatz** [comment]
@rwjblue,  We inject ember source file through `ember-cli-build` file by including in vendor folder. This would be the case if the ember version is below 2.12 (before `ember-source`). In that case, dependency checker will fail to fetch the version. Any recommendation for this?

**Comment by rwjblue** [comment]
@Turbo87 - you are correct, this issue is already resolved
