### ISSUE TITLE
Basedir confusion

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli-version-checker#140]
This library's API has an ambiguity that causes subtle problems, most of which are glossed over by the accidental behavior of node_modules, but will cause increasing trouble under PnP or when using npm linking.

The default place we resolve from is the addon's own root directory:

https://github.com/ember-cli/ember-cli-version-checker/blob/81bd32c39248a256f0b8ce9d71a30019a83ca7c7/src/npm-dependency-version-checker.js#L12

But that's rarely the right place. The only case in which it's correct is when you have an explicit peerDependency and you want to double-check that it's satisfied.

Otherwise, you almost always want to be doing either:
  1. Resolution from your parent package's root: to check for a thing that is treated like a peerDependency, but not explicitly listed as one. If it's not listed, NPM won't guarantee it's actually resolvable from our own root, so checking from our parent package's root is necessary. 
  2. A search through all active addons: to check whether a particular package is present in the entire application. Checking resolvability from only the top-level project isn't really correct ("is ember-data present?" can't truly be answered by checking whether it's resolvable by the app, maybe it's pulled in by another addon and NPM doesn't guarantee ember-data will be resolvable from the app in that case).

This bug is hidden by the fact that *usually* most things are resolvable from the addon that happens to be asking the question, but only by accident of it being nested in the right place under node_modules.

It may be desirable to make these different kinds of questions explicit in this library's API. I think the existing calls are all really uses of scenario 2 above: they want to search through the dependencies of all active addons.

**Comment by rwjblue** [comment]
I don't think this analysis is quite correct 😸 

The issue that you had in https://github.com/ember-animation/ember-animated/commit/505a4a6b514aeacff1faa706d345b1846b21548b is because the wrong argument was passed in. `this` should **_basically_ never** be passed in to `ember-cli-version-checker`, instead `this.parent` or `this.project` should be passed.

**Comment by rwjblue** [comment]
Unfortunatley, our own docs have this wrong 😭

**Comment by ef4** [comment]
I see. Yeah, that does help with some of the cases. But not quite all of them.

Consider:

 - addonA wants to check if ember-data is present in the app
 - app depends on addonA and addonB
 - addonB depends on ember-data
 - app doesn't depend on ember-data
 - addonB doesn't depend on addonA

The only place that's guaranteed to be able to resolve ember-data is addonB's root. But addonB is neither `this.project` nor `this.parent`.

An easy way to break this in practice is to run the app with `yarn link addonB`. That will cause the dependency checker to not find ember-data, even though it's getting included correctly in the app.

**Comment by stefanpenner** [comment]
I believe the following changes introduced by https://github.com/ember-cli/ember-cli-version-checker/pull/156 improved this situation.

* https://github.com/ember-cli/ember-cli-version-checker#hassingleimplementation
* https://github.com/ember-cli/ember-cli-version-checker#assertsingleimplementation
* https://github.com/ember-cli/ember-cli-version-checker#assertsingleimplementation
* https://github.com/ember-cli/ember-cli-version-checker#note

--

If i misunderstood, please let me know and help me understand why so we can adjust accordingly.
