### ISSUE TITLE
assertAbove throws error on exact match of version

### ISSUE THREAD

**Issue by jme783** [ember-cli/ember-cli-version-checker#16]
https://github.com/rwjblue/ember-cli-version-checker/blob/bf010c726d0c3be9131fc25a2a247beb1f89895c/index.js#L62

Shouldn't this statement be: `return semver.gte(this.version, compareVersion);` to be inclusive of the version specified?

**Comment by Turbo87** [comment]
in that case it should IMHO be named `isAboveOrEqual()`.

but you are correct that the deprecated static `isAbove()` method did it differently: https://github.com/ember-cli/ember-cli-version-checker/blob/bf010c726d0c3be9131fc25a2a247beb1f89895c/index.js#L121-L125
