### ISSUE TITLE
Addon installation crashes with: [ember-cli-version-checker] 'checker.forEmber' has been removed, please use 'checker.for(`ember-source`)'

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli-version-checker#237]
`ember i ember-cli flash` [yields](https://github.com/poteto/ember-cli-flash/issues/340) this:

```
  - stack: Error: [ember-cli-version-checker] 'checker.forEmber' has been removed, please use 'checker.for(`ember-source`)'
    at VersionChecker.forEmber (C:\Code\kaliber5\test-app\node_modules\ember-cli-version-checker\src\version-checker.js:26:11)
    at Class.afterInstall (C:\Code\kaliber5\test-app\node_modules\ember-cli-flash\blueprints\ember-cli-flash\index.js:14:25)
...
```

The worst part is that `ember-cli-version-checker`'s [changelog](https://github.com/ember-cli/ember-cli-version-checker/blob/master/CHANGELOG.md) mentions neither deprecation nor removal of `forEmber`. 😒

**Comment by lolmaus** [comment]
To work around the issue, add this to the host app:

```js
  "resolutions": {
    "ember-cli-version-checker": "^4.0.0"
  }
```

**Comment by wagenet** [comment]
Removed in f0c28e29146a760ffb9456f5a0d66967424f7841.

**Comment by wagenet** [comment]
@lolmaus it is mentioned in the CHANGELOG for 5.0 under "remove unneeded features" https://github.com/ember-cli/ember-cli-version-checker/blob/master/CHANGELOG.md#v500-2020-02-14.

**Comment by rwjblue** [comment]
Sorry for missing this when you opened it @lolmaus, this isn't a bug that API was intentionally removed in a breaking change release.
