### ISSUE TITLE
Expose `gte` and other useful semver methods

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-version-checker#30]
Currently only `gt`, `lt` and `satisfies` are exposed.

**Comment by rwjblue** [comment]
Seems good to expose some, but I don't want to expose all of the possible `semver` methods.  

We should just list out the ones we want...

**Comment by Turbo87** [comment]
I'd say: gt, lt, gte, lte, eq, neq, satisfies

**Comment by rwjblue** [comment]
ya, those seem good to me
