### ISSUE TITLE
Detects incorrect Ember version with `npm link` or `yarn link`

### ISSUE THREAD

**Issue by pzuraq** [ember-cli/ember-cli-version-checker#45]
I'm still not 100% sure of what's going on here, so I'm making an issue to track what I think it is.

Given something like the following in an addon:

```js
included(parent) {
  const host = this._findHost();

  emberChecker = new VersionChecker(host).forEmber();
}
```

The symptoms are that when linking the addon for development in a project using `yarn link`, the emberChecker will instead return the version of Ember included in the _addon's_ devDependencies. I think in this case, it is because `host` is an EmberApp, and it doesn't have a `root` value (logging shows it is `undefined`), which leads to `resolve` following the normal resolution rules and resolving from the current project (the everlasting problem with `link` everywhere 😛 )

What's interesting is that this doesn't break and appears to work correctly when not-linked, and even when we do:

```js
included(parent) {
  emberChecker = new VersionChecker(parent).forEmber();
}
```

Seems counterintuitive at first, but I guess even though we are resolving the `ember-source` version from the immediate parent addon, because it's not installed as a normal dependency it ends up resolving to the host's (intended behavior?)

**Comment by rwjblue** [comment]
I'm pretty sure this was fixed by https://github.com/ember-cli/ember-cli-version-checker/pull/53.

Happy to reopen if not...
