### ISSUE TITLE
Absolute path for directory in .bowerrc breaks version checking

### ISSUE THREAD

**Issue by rvfischione** [ember-cli/ember-cli-version-checker#46]
[This](https://github.com/ember-cli/ember-cli-version-checker/blob/master/src/bower-dependency-version-checker.js#L18) assumes a project will have its bower_components directory in the same parent directory as its bower.json. If the directory entry in .bowerrc is an absolute path, this addon will fail to find the bower.json file. This is inconsistent with behavior of `bower install` with the same .bowerrc and bower.json.

One supporting use case is having a shared bower_components directory across a number of projects in a development sandbox. Thoughts?

**Comment by rwjblue** [comment]
In that case, I would expect `project.bowerDirectory` to be the absolute path?  Would we just need to tweak things around so that we use `path.resolve` instead of `path.join`?

**Comment by dmcalderon** [comment]
https://github.com/bower/bower/pull/2130/files

That does look like how the .bowerrc change was accomplished.

**Comment by rvfischione** [comment]
@rwjblue Yes, sorry for not clarifying. `project.bowerDirectory` is resolved from .bowerrc (see [here](https://github.com/ember-cli/ember-cli/blob/4cdb017ce5341578d0ce950874c50463cbb64c56/lib/models/project.js#L96)). `path.resolve` whould work for getting the bower_components folder, though the logic for retrieving bower.json from the app directory would need to be retained, something like [this](https://github.com/ember-cli/ember-cli/blob/4cdb017ce5341578d0ce950874c50463cbb64c56/lib/models/project.js#L386).

**Comment by stefanpenner** [comment]
Since we do not support bower any more, I suspect this can be dropped. Closing this, but if I am closing in error let me know.
