### ISSUE TITLE
Deprecation warning when running ember 2.18.0

### ISSUE THREAD

**Issue by waissbluth** [ember-cli/ember-cli-version-checker#48]
I've been getting this error on an emver 2.18.0 app:
```
$ ember -v
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (~/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
ember-cli: 2.18.0
node: 9.2.1
os: darwin x64
```

**Comment by rwjblue** [comment]
The current versions of this package do not have this issue. I’d suggest doing `npm ls `Ember-cli-version-checker` and updating all packages that depend on versions older than 2.0.0...

**Comment by jacobq** [comment]
@stonecircle, would you please consider cutting another release of `ember-cli-notifications`? This problem seems to affect the current one (v4.2.1) but is fixed in `master` (thanks to https://github.com/stonecircle/ember-cli-notifications/pull/180 and https://github.com/stonecircle/ember-cli-notifications/pull/184 ).

**Comment by jacobq** [comment]
@lukemelia Please consider cutting another release `ember-tether` to incorporate https://github.com/yapplabs/ember-tether/commit/313bc1593a373f988d73be9365da53275df218ee which resolves this issue.

**Comment by corrspt** [comment]
@rwjblue What do I do, if the only thing using `ember-cli-version-checker` under 2.0 is `ember-cli` itself? Do I have to migrate to `ember-cli` 3.0?

```javascript
ember-cli@2.18.0
│ ├─┬ ember-cli-legacy-blueprints@0.2.1
│ │ └── ember-cli-version-checker@2.1.0 
│ └─┬ ember-try@0.2.17
│   └── ember-cli-version-checker@1.3.1 
```

**Comment by jacobq** [comment]
@corrspt e-cli 2.18.0 uses `"ember-try": "^0.2.15"` so if you `nombom` (or `yarn upgrade`) I think that it should get v0.2.23  (v0.2.21 and newer incorporate [a PR to upgrade `ember-cli-version-checker`](https://github.com/ember-cli/ember-try/pull/165)) and that one will go away. (and your snippet shows `ember-cli-legacy-blueprints` on 2.x already).

**Comment by corrspt** [comment]
Thanks @jacobq . Now my `npm ls ember-cli-version-checker` shows things differently and I see several addons using (though their dependencies) a version < 2.

```js
├─┬ ember-cli-babel@6.11.0
│ └── ember-cli-version-checker@2.1.0 
├─┬ ember-cli-build-notifications@0.2.0
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-font-awesome@3.0.5
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-light-table@1.11.0
│ ├─┬ ember-in-viewport@2.1.1
│ │ └─┬ ember-cli-babel@5.2.4
│ │   └── ember-cli-version-checker@1.3.1 
│ └─┬ ember-scrollable@0.4.11
│   ├─┬ ember-component-inbound-actions@1.2.1
│   │ └─┬ ember-cli-babel@5.2.4
│   │   └── ember-cli-version-checker@1.3.1 
│   └─┬ ember-element-resize-detector@0.1.5
│     └─┬ ember-cli-babel@5.2.4
│       └── ember-cli-version-checker@1.3.1 
├─┬ ember-pikaday@2.2.4
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-plupload@1.13.19
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-radio-button@1.2.2
│ ├─┬ ember-cli-babel@6.12.0
│ │ └── ember-cli-version-checker@2.1.0 
│ └─┬ ember-cli-htmlbars@1.3.4
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-responsive@2.0.5
│ ├─┬ ember-cli-babel@6.12.0
│ │ └── ember-cli-version-checker@2.1.0 
│ └─┬ ember-getowner-polyfill@1.2.5
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-simple-auth-token@2.1.0
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
├─┬ ember-suave@4.0.1
│ ├─┬ broccoli-jscs@2.0.0
│ │ └── ember-cli-version-checker@1.3.1 
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
└─┬ ember-tooltips@2.9.2
  ├─┬ ember-cli-babel@6.12.0
  │ └── ember-cli-version-checker@2.1.0 
  ├─┬ ember-cli-htmlbars@1.3.4
  │ └── ember-cli-version-checker@1.3.1 
  ├─┬ ember-cli-sass@7.1.7
  │ └── ember-cli-version-checker@2.1.0 
  └─┬ ember-hash-helper-polyfill@0.1.2
    └── ember-cli-version-checker@1.3.1 
```

I'll have to go through each of them, but at least now I have a plan :) Thanks very much @jacobq

**Comment by jacobq** [comment]
Note that you can run `npm ls ember-cli-version-checker@1` to suppress the 2.x versions from the list. If you use [`yarn`](https://yarnpkg.com/) you might also be able to work around this using the [selective version resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) feature. Personally though, I think it's nicest for the whole community to submit PRs that update ember-cli (checkout the [`ember-cli-update`](https://github.com/kellyselden/ember-cli-update) to make the process much smoother) for addons triggering this warning.

**Comment by corrspt** [comment]
Thanks very much for the tips @jacobq. I agree that we should do that (submitting the PR's)... I'll try to find the time to contribute back 👍

**Comment by Turbo87** [comment]
I'll go ahead and close this issue as it is not an issue in this project itself, but instead in all the projects using it.
