### ISSUE TITLE
Is it possible to backport the project.nodeModulesPath fix to 1.3.1?

### ISSUE THREAD

**Issue by ctusch** [ember-cli/ember-cli-version-checker#50]
A lot of inactive Ember addons are using pre 2.0.0 ember-cli-version-checker (often through an old version of ember-cli-htmlbars). This leads to the known deprecation message during build:

    DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }).

This was fixed in 2.0.0 by using said resolve.sync. Would it be possible to backport this change to 1.3.1 and release it as 1.3.2? Or would it for some reason break backward compatibility?

This would fix the deprecation message at least for all the addons I'm having trouble with. Using yarn's dependency resolution feature doesn't help since 2.0.0 seems to have some incompatible API changes (which in a semver world makes sense).

**Comment by rwjblue** [comment]
Unfortunately, moving from assumptions about `project.nodeModulesPath` to "true" node resolution _was_ one of the main breaking changes in 2.0...
