### ISSUE TITLE
Public api to check whether a dependency exists

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-cli-version-checker#8]
I'm trying to use `ember-cli-version-checker` to determine if a host app has `liquid-fire` installed. If the host app doesn't, and I run

``` js
var checker = new VersionChecker(this);
var dep = checker.for('aliquid-fire', 'npm');

console.log(dep.gt('0.17.0'));
```

then `dep.gt('0.17.0')` throws an error.

Is there a public api to see whether the dependency is even installed? And if not, would you accept a PR for one?

**Comment by rwjblue** [comment]
You can check `dep.version` (which should be `null` if not present).

**Comment by rwjblue** [comment]
does that throw?

**Comment by samselikoff** [comment]
Also, I'm trying to use this to update the host app's config. Since `VersionChecker` requires the addon instance during instantiation, what's the best way to do this?

We came up with

```js
// config/environment.js
/* jshint node: true */
'use strict';

var VersionChecker = require('ember-cli-version-checker');

module.exports = function( environment, appConfig, addon ) {
  appConfig['ember-collapsible-panel'] = appConfig['ember-collapsible-panel'] || {};

    var checker = new VersionChecker(addon);
    var dep = checker.for('liquid-fire', 'npm');
    var hasLiquidFire = false;

    try {
      if (dep.gt('0.17.0')) {
        hasLiquidFire = true;
      }
    } catch(e) {

    }

  appConfig['ember-collapsible-panel']['hasLiquidFire'] = hasLiquidFire;

  return appConfig;
};
```

which feels hacky

**Comment by samselikoff** [comment]
Yep `dep.version` works, thanks!

**Comment by rwjblue** [comment]
Ideally you can do:

```javascript
'use strict';

var VersionChecker = require('ember-cli-version-checker');

module.exports = function( environment, appConfig, addon ) {
  var checker = new VersionChecker(addon);
  var dep = checker.for('liquid-fire', 'npm');

  appConfig['ember-collapsible-panel'] = appConfig['ember-collapsible-panel'] || {
    hasLiquidFire: !!dep.version
  };

  return appConfig;
};
```

**Comment by Turbo87** [comment]
@rwjblue we should either document `version` as public API somewhere or expose an `exists()` method or something like that

**Comment by rwjblue** [comment]
I’m happy to do both. Add .exists() _and_ document .version.

**Comment by rwjblue** [comment]
Done!

https://github.com/ember-cli/ember-cli-version-checker#exists

https://github.com/ember-cli/ember-cli-version-checker#version
