### ISSUE TITLE
Resolution can fail in yarn workspaces

### ISSUE THREAD

**Issue by pzuraq** [ember-cli/ember-cli-version-checker#93]
In workspaces, when a package is hoisted and using `ember-cli-version-checker`, it can fail by accidentally checking the version in the root rather than the version in sub packages: [ref](https://discordapp.com/channels/480462759797063690/485254664032485395/545313482116038690)

For now the solution appears to using `nohoist` on the offending package, but ideally we could figure out a way to tell what the correct resolution should be.

**Comment by rwjblue** [comment]
Thanks for reporting! I think the first step here would be creating a smallish reproduction, then we can figure out how normal `require`'s within a JS file work. Then we can figure out where we are going wrong...

**Comment by pzuraq** [comment]
Repro here: https://github.com/betocantu93/monorepo-decorators, major thanks to @betocantu93!

**Comment by buschtoens** [comment]
Didn't I fix this in #70? 🤔

**Comment by betocantu93** [comment]
I can confirm @ember-decorators/babel-transforms 5.1.3 works, as suggested in #70, but right now `ember install ember-decorators` installs the 3.1.0 version

https://github.com/ember-decorators/ember-decorators/blob/23c55cc279f1e3715a742836a55c74883042feaa/packages/-ember-decorators/blueprints/ember-decorators/index.js#L74

**Comment by buschtoens** [comment]
So I guess we can close this issue here?
